/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_version_3;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.print.PrinterException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 *
 * @author trido
 */
public class BillingDashBoard extends javax.swing.JFrame {
    private static ContainInformation containInformation = new ContainInformation();
    private static double total;
    private static final double TAX = 0.1;
    private static final double SHIPPING_FEES = 6.25;
    private static DecimalFormat df = new DecimalFormat("#.##");
    private static ArrayList<Item> items;
    
    // capture the information order to send back when the user click Back button
    private static Order order;
    /**
     * Creates new form BillingDashBoard
     */
    public BillingDashBoard() {
        initComponents();
    }
    
    //delete
    public BillingDashBoard(ArrayList<Item> item) {
        initComponents();
    }
    
    public BillingDashBoard(double total, Order order, ArrayList<Item> items){
        initComponents();
        this.total = total;
        setTotal1();
        setTotal2();
        receiptArea.append(printReceipt()+order.printAllItems());
        this.order = order;
        this.items = items;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        confirmBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        radioPickup = new javax.swing.JRadioButton();
        radioDelivery = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phoneField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        subtotal1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        customerField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        errorName1 = new javax.swing.JLabel();
        errorPhone1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        customerField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phoneField2 = new javax.swing.JTextField();
        billingField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deliveryField = new javax.swing.JTextField();
        errorName2 = new javax.swing.JLabel();
        errorPhone2 = new javax.swing.JLabel();
        errorDelivery = new javax.swing.JLabel();
        errorBilling2 = new javax.swing.JLabel();
        subtotal2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        addressCheckbox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        printReceiptbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));

        confirmBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Checkmark_1891021.png"))); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_37Ago_arrow_arrow_left_back_previous_direction_left_1886135 (2).png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_close_1282956.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioPickup);
        radioPickup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radioPickup.setForeground(new java.awt.Color(0, 102, 153));
        radioPickup.setText("Pickup");
        radioPickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPickupActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioDelivery);
        radioDelivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radioDelivery.setForeground(new java.awt.Color(0, 102, 153));
        radioDelivery.setText("Delivery");
        radioDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDeliveryActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Tax");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Total");

        phoneField1.setEnabled(false);
        phoneField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Subtotal");

        subtotal1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        subtotal1.setForeground(new java.awt.Color(0, 153, 0));
        subtotal1.setText("$0.00");

        total1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        total1.setForeground(new java.awt.Color(0, 153, 0));
        total1.setText("$0.00");

        customerField1.setEnabled(false);
        customerField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Customer's Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Phone: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("10%");

        errorName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorName1.setForeground(new java.awt.Color(204, 0, 51));
        errorName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        errorPhone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorPhone1.setForeground(new java.awt.Color(204, 0, 51));
        errorPhone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total1)
                            .addComponent(jLabel11)
                            .addComponent(subtotal1))
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(phoneField1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(customerField1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(errorName1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(errorPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(customerField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(errorName1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(errorPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(subtotal1))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total1))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Phone: ");

        customerField2.setEnabled(false);
        customerField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerField2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Total");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Subtotal");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Tax");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Customer's Name:");

        phoneField2.setEnabled(false);
        phoneField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneField2ActionPerformed(evt);
            }
        });

        billingField.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Billing Address");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Delivery Fees");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Delivery Address:");

        deliveryField.setEnabled(false);

        errorName2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorName2.setForeground(new java.awt.Color(204, 0, 51));
        errorName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        errorPhone2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorPhone2.setForeground(new java.awt.Color(204, 0, 51));
        errorPhone2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        errorDelivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorDelivery.setForeground(new java.awt.Color(204, 0, 51));
        errorDelivery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        errorBilling2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorBilling2.setForeground(new java.awt.Color(204, 0, 51));
        errorBilling2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        subtotal2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        subtotal2.setForeground(new java.awt.Color(0, 153, 0));
        subtotal2.setText("$0.00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("10%");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setText("$6.25");

        total2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        total2.setForeground(new java.awt.Color(0, 153, 0));
        total2.setText("$0.00");

        addressCheckbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressCheckbox.setText("Address & Billing Address are the same");
        addressCheckbox.setEnabled(false);
        addressCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                addressCheckboxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addressCheckbox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel16))
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(subtotal2)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel17))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(total2)
                                                    .addComponent(jLabel20))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(billingField)
                                        .addGap(5, 5, 5)))
                                .addComponent(errorBilling2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(phoneField2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(customerField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                                    .addComponent(deliveryField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(errorPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(errorDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errorName2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(5, 5, 5))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorName2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(customerField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(errorPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(errorDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(deliveryField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressCheckbox)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(errorBilling2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(billingField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(subtotal2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(total2))
                .addContainerGap())
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_10_Delivery_1871427 (1).png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_10_avatar_2754575.png"))); // NOI18N

        message.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        message.setForeground(new java.awt.Color(204, 0, 51));
        message.setText(" ");

        receiptArea.setColumns(20);
        receiptArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        receiptArea.setRows(5);
        receiptArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jScrollPane1.setViewportView(receiptArea);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Receipt");

        printReceiptbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printReceiptbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cutlery.png"))); // NOI18N
        printReceiptbtn.setText("Finish Transaction");
        printReceiptbtn.setEnabled(false);
        printReceiptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPickup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(236, 236, 236))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioDelivery))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(confirmBtn)
                                .addGap(46, 46, 46)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printReceiptbtn)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioPickup)
                            .addComponent(message)
                            .addComponent(jLabel12)))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioDelivery)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel13))
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(printReceiptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneField1ActionPerformed

    private void radioPickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPickupActionPerformed
        // TODO add your handling code here:
        setPickup();
    }//GEN-LAST:event_radioPickupActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        changeToAnotherWindow();
    }//GEN-LAST:event_backBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        String customer;
        String phoneNumber;
        
        // Initialize the error fields to null
        errorName1.setText(null);
        errorPhone1.setText(null);
        
        errorName2.setText(null);
        errorPhone2.setText(null);
        errorDelivery.setText(null);
        errorBilling2.setText(null);
        
        // variable to control validation
        boolean checkValidation = true;
        
        // If Pickup is selected
        if(radioPickup.isSelected()){
            
            customer = customerField1.getText();
            phoneNumber = phoneField1.getText();
            
            // Check if user enter the fields
            if(customer.length() < 1 ){
                errorName1.setText("*");
                checkValidation = false;
            }
            if(phoneNumber.length() < 1){
                errorPhone1.setText("*");
                checkValidation = false;
            }
            if(checkValidation == true){
                containInformation.addInformation(new Information(customer, phoneNumber, total));
                
                receiptArea.append("\n\t\t\t\t\tTotal: " + total1.getText());
                printInformation();
                setDisableBtn();
            }else{
                JOptionPane.showMessageDialog(new JFrame(), "Please fill out the inputs", "Error", JOptionPane.ERROR_MESSAGE);
               
            } 
        }
        
        
        // If Delivery is selected
        if(radioDelivery.isSelected()){
            customer = customerField2.getText();
            phoneNumber = phoneField2.getText();            
            String deliveryAddress = deliveryField.getText();
            String billing = billingField.getText();
            
            if(customer.length() < 1 ){
                errorName2.setText("*");
                checkValidation = false;
            }
            if(phoneNumber.length() < 1){
                errorPhone2.setText("*");
                checkValidation = false;
            }
            if(deliveryAddress.length() < 1){
                errorDelivery.setText("*");
                checkValidation = false;
            }
            if(!addressCheckbox.isSelected()){
                if(billing.length() < 1){
                    errorBilling2.setText("*");
                    checkValidation = false;
                }
            }
            if(checkValidation == true){
                containInformation.addInformation(new Information(customer, phoneNumber, total, deliveryAddress, billing));
                
                receiptArea.append("\n\t\t\t\t\tTotal: " + total2.getText());
                printInformation();
                setDisableBtn();
            }else{
                JOptionPane.showMessageDialog(new JFrame(), "Please fill out the inputs", "Error", JOptionPane.ERROR_MESSAGE);
               
            }            
        }

    }//GEN-LAST:event_confirmBtnActionPerformed

    private void customerField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_customerField1ActionPerformed

    private void radioDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDeliveryActionPerformed
        // TODO add your handling code here:
        setDelivery();
    }//GEN-LAST:event_radioDeliveryActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Do you want to exit???", "Exit", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void phoneField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneField2ActionPerformed

    private void customerField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerField2ActionPerformed

    private void addressCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_addressCheckboxStateChanged
         addressCheckbox.addItemListener(new ItemListener() {
             @Override
             public void itemStateChanged(ItemEvent e) {
                 if(e.getStateChange() == ItemEvent.SELECTED){
                    String deliveryAddress = deliveryField.getText();
                    billingField.setText(deliveryAddress);
                    billingField.setEditable(false);
                 }else{
                    billingField.setText(null);
                    billingField.setEditable(true); 
                 }
             }
         });
    }//GEN-LAST:event_addressCheckboxStateChanged

    private void printReceiptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptbtnActionPerformed

        clearAlldata();

    }//GEN-LAST:event_printReceiptbtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addressCheckbox;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField billingField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField customerField1;
    private javax.swing.JTextField customerField2;
    private javax.swing.JTextField deliveryField;
    private javax.swing.JLabel errorBilling2;
    private javax.swing.JLabel errorDelivery;
    private javax.swing.JLabel errorName1;
    private javax.swing.JLabel errorName2;
    private javax.swing.JLabel errorPhone1;
    private javax.swing.JLabel errorPhone2;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JTextField phoneField1;
    private javax.swing.JTextField phoneField2;
    private javax.swing.JButton printReceiptbtn;
    private javax.swing.JRadioButton radioDelivery;
    private javax.swing.JRadioButton radioPickup;
    private javax.swing.JTextArea receiptArea;
    private javax.swing.JLabel subtotal1;
    private javax.swing.JLabel subtotal2;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables

    public void setDelivery(){
        customerField2.setEnabled(true);
        phoneField2.setEnabled(true);
        deliveryField.setEnabled(true);
        billingField.setEnabled(true);
        addressCheckbox.setEnabled(true);
        
        customerField1.setEnabled(false);
        phoneField1.setEnabled(false); 
    }
    
    public void setPickup(){
        customerField1.setEnabled(true);
        phoneField1.setEnabled(true);
        
        customerField2.setEnabled(false);
        phoneField2.setEnabled(false);
        deliveryField.setEnabled(false);
        billingField.setEnabled(false);
        addressCheckbox.setEnabled(false);
    }
    
    // total of Pick up
    public void setTotal1(){

        double finalTotal = this.total + (this.total * TAX);
        String finalTotal_String = df.format(finalTotal);
        
        // total before tax
        subtotal1.setText("$"+df.format(this.total));
        
        // total after tax
        total1.setText("$"+ (finalTotal_String));
    }
    
    // total of Delivery
    public void setTotal2(){

        double finalTotal = this.total + (this.total * TAX) + SHIPPING_FEES;
        
        // get 2 digits from the value
        String finalTotal_String = df.format(finalTotal);
        
        // total before tax
        subtotal2.setText("$" + df.format(this.total));
        
        // total after tax + shipping fees
        total2.setText("$" + (finalTotal_String));
    }
    
    public String printReceipt(){
        return String.format("\t\t           ****\n\n\n"
                + "\t\t     ToGo's Restaurent\n"
                + "\t\t       (460)-777-3423\n"
                + "\t\t3562 1ST MATHTHEW RD, NEW YORK\n\n"
                + "\t\t       TOGO #12 / 3725\n"
                + "\t-------------------------------------------\n\n"
                + "  Name\t\t\t   Qty\t\t  Price\n\n"
                
        );
                
    }
    
    public void printInformation(){
        String name = containInformation.printInformation().getName();
        String phone = containInformation.printInformation().getPhoneNumber();
        String deliveryAddress = containInformation.printInformation().getAddress();
        String billingAddress = containInformation.printInformation().getBillingAddress();
        if(deliveryAddress == null){
           receiptArea.append("\n\nName: " + name + "\nPhone: " +phone);
        }else{
            receiptArea.append("\n\nName: " + name + "\nPhone: " +phone
                                + "\nAddress: " + deliveryAddress
                                + "\nBilling Address: " + billingAddress);
        }
    }
    
    public void changeToAnotherWindow(){
        // pass arraylist back to the menu
        String subtotal_String = subtotal2.getText().replace("$", ""); 
        double subtotal = Double.parseDouble(subtotal_String);
        Menu menu = new Menu(items, subtotal);
        this.containInformation.clearInformation();
        this.order.clearData();
        menu.setVisible(true);
        this.setVisible(false);
    }
    
    
    // set the enable/disable button 
    public void setDisableBtn(){
        printReceiptbtn.setEnabled(true);
        backBtn.setEnabled(false);
        radioPickup.setEnabled(false);
        radioDelivery.setEnabled(false);
        confirmBtn.setEnabled(false);
    }
    
    // clear all data when user click finish and go back into the main menu
    public void clearAlldata(){
        this.order.clearData();
        this.containInformation.clearInformation();
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }
}
